# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FSCalendarSwiftExample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FSCalendarSwiftExample
  pod 'Charts'  
  pod 'SwiftProtobuf', '~> 1.0'
  pod 'Bluejay', :git => 'https://github.com/steamclock/bluejay.git', :branch => 'master'


 target 'FSCalendarSwiftExampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
