/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.0-dev at Tue Mar  6 15:15:15 2018. */

#include "message.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t Msg_fields[2] = {
    PB_FIELD(  2, STRING  , REQUIRED, STATIC  , FIRST, Msg, val, val, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
