# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='data.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\ndata.proto\"J\n\x08GoYoData\x12\x0f\n\x07x_accel\x18\x01 \x02(\x05\x12\x0f\n\x07y_accel\x18\x02 \x02(\x05\x12\x0f\n\x07z_accel\x18\x03 \x02(\x05\x12\x0b\n\x03\x66sr\x18\x04 \x02(\x05')
)




_GOYODATA = _descriptor.Descriptor(
  name='GoYoData',
  full_name='GoYoData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x_accel', full_name='GoYoData.x_accel', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y_accel', full_name='GoYoData.y_accel', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='z_accel', full_name='GoYoData.z_accel', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fsr', full_name='GoYoData.fsr', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=88,
)

DESCRIPTOR.message_types_by_name['GoYoData'] = _GOYODATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GoYoData = _reflection.GeneratedProtocolMessageType('GoYoData', (_message.Message,), dict(
  DESCRIPTOR = _GOYODATA,
  __module__ = 'data_pb2'
  # @@protoc_insertion_point(class_scope:GoYoData)
  ))
_sym_db.RegisterMessage(GoYoData)


# @@protoc_insertion_point(module_scope)
