/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.0-dev at Mon Mar 12 22:29:14 2018. */

#ifndef PB_DATA_PB_H_INCLUDED
#define PB_DATA_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _GoYoData {
    int32_t x_accel;
    int32_t y_accel;
    int32_t z_accel;
    int32_t fsr;
/* @@protoc_insertion_point(struct:GoYoData) */
} GoYoData;

/* Default values for struct fields */

/* Initializer values for message structs */
#define GoYoData_init_default                    {0, 0, 0, 0}
#define GoYoData_init_zero                       {0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define GoYoData_x_accel_tag                     1
#define GoYoData_y_accel_tag                     2
#define GoYoData_z_accel_tag                     3
#define GoYoData_fsr_tag                         4

/* Struct field encoding specification for nanopb */
extern const pb_field_t GoYoData_fields[5];

/* Maximum encoded size of messages (where known) */
#define GoYoData_size                            44

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define DATA_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
