/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.0-dev at Mon Mar 12 22:29:14 2018. */

#include "data.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t GoYoData_fields[5] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, GoYoData, x_accel, x_accel, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, GoYoData, y_accel, x_accel, 0),
    PB_FIELD(  3, INT32   , REQUIRED, STATIC  , OTHER, GoYoData, z_accel, y_accel, 0),
    PB_FIELD(  4, INT32   , REQUIRED, STATIC  , OTHER, GoYoData, fsr, z_accel, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
