/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.0-dev at Thu Mar  8 15:46:47 2018. */

#include "datapig.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t Data_fields[5] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, Data, x_accel, x_accel, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, Data, y_accel, x_accel, 0),
    PB_FIELD(  3, INT32   , REQUIRED, STATIC  , OTHER, Data, z_accel, y_accel, 0),
    PB_FIELD(  4, INT32   , REQUIRED, STATIC  , OTHER, Data, fsr, z_accel, 0),
    PB_LAST_FIELD
};

const pb_field_t DataPig_fields[2] = {
    PB_FIELD(  1, MESSAGE , REPEATED, CALLBACK, FIRST, DataPig, data, data, &Data_fields),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
