/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.0-dev at Thu Mar  8 15:46:47 2018. */

#ifndef PB_DATAPIG_PB_H_INCLUDED
#define PB_DATAPIG_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _DataPig {
    pb_callback_t data;
/* @@protoc_insertion_point(struct:DataPig) */
} DataPig;

typedef struct _Data {
    int32_t x_accel;
    int32_t y_accel;
    int32_t z_accel;
    int32_t fsr;
/* @@protoc_insertion_point(struct:Data) */
} Data;

/* Default values for struct fields */

/* Initializer values for message structs */
#define Data_init_default                        {0, 0, 0, 0}
#define DataPig_init_default                     {{{NULL}, NULL}}
#define Data_init_zero                           {0, 0, 0, 0}
#define DataPig_init_zero                        {{{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define DataPig_data_tag                         1
#define Data_x_accel_tag                         1
#define Data_y_accel_tag                         2
#define Data_z_accel_tag                         3
#define Data_fsr_tag                             4

/* Struct field encoding specification for nanopb */
extern const pb_field_t Data_fields[5];
extern const pb_field_t DataPig_fields[2];

/* Maximum encoded size of messages (where known) */
#define Data_size                                44
/* DataPig_size depends on runtime parameters */

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define DATAPIG_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
